Add Sports Standings app
tidbyt/community pull request #105
Opened 2022-01-25 04:01 UTC by rs7q5

This app displays sports standings for various sports (currently only MLB and NHL, sothe important ones :) ). 

currently set to pull every 24 hours as well.

![sports_standings](https://user-images.githubusercontent.com/46969733/150908611-c2dd05d7-f56b-4488-b66d-89a5d56f992e.gif)

2022-01-25 07:20 UTC, rs7q5 commented
If there's enough need, I could add more sports, but I wasn't sure what you're guys' plans were. 

I don't think it would be hard or take long for me to add additional sports, since the frames are created expecting a particular format. 

Also, I didn't want to sit on this while the NHL season is in full swing.

2022-02-01 20:50 UTC, rohansingh requested changes
Just a few minor changes. If they look good to you, please commit them and we can merge. Thanks 😺

2022-02-01 20:50 UTC, rohansingh commented on apps/sportsstandings/sports_standings.star
> +    stats_cached = cache.get("stats_rate")
Cache key should include `sport` so we have a different cache for each sport.

```suggestion
    stats_cached = cache.get("stats_rate/%s" % sport)
```

2022-02-01 20:50 UTC, rohansingh commented on apps/sportsstandings/sports_standings.star
> +        cache.set("stats_rate", json.encode(stats), ttl_seconds = 86400)  #grabs it once a day
```suggestion
        cache.set("stats_rate/%s" % sport, json.encode(stats), ttl_seconds = 86400)  #grabs it once a day
```

2022-02-01 20:50 UTC, rohansingh commented on apps/sportsstandings/sportsstandings.go
> +		Desc:        "Get various sports standings (currently only MLB and NHL).",
Just updating the description to match the other update.
```suggestion
		Desc:        "Get various sports standings (data courtesy of ESPN).",
```

2022-02-01 21:34 UTC, merged