SF Transit Bart and Muni Applet for Tidbyt
tidbyt/community pull request #1091
Opened 2023-02-08 05:31 UTC by hassoncs

Displays predicted arrival times for both Muni and Bart at the same time. Now you can decide way to head to at a glance when you are leaving the house!

Estimates comes from the [NextBus](https://www.nextbus.com) API for [San Francisco Muni](https://www.sfmta.com/) and the [Bart Legacy API](https://www.bart.gov/schedules/developers/api) for [Bart](https://www.bart.gov/).

There are are few configuration options:
* Set both a bart station and muni stop
* Hide arrival times below a certain number of minutes (so you have time to get there)

![sf_bart_muni](https://user-images.githubusercontent.com/5104925/217442580-32c04621-7c44-4972-a828-44c334bd4c35.gif)

2023-02-08 05:31 UTC, hassoncs commented
I have read the CLA Document and I hereby sign the CLA

2023-02-08 05:35 UTC, hassoncs commented
I have read the CLA Document and I hereby sign the CLA

2023-02-08 05:35 UTC, hassoncs commented
recheck

2023-02-21 19:39 UTC, matslina requested changes

2023-02-21 19:39 UTC, matslina commented on apps/sfbartmuni/manifest.yaml
> +id: sf-next-muni
```suggestion
id: sf-bart-muni
```

2023-02-21 19:39 UTC, matslina commented on apps/sfbartmuni/sf_bart_muni.star
> +def configure(config):
Could you help me understand why you're using the cache for this?

2023-02-21 19:39 UTC, matslina commented on apps/sfbartmuni/sf_bart_muni.star
> +    all_muni_stops = fetch_data(get_all_stops_url, get_all_stops_url)
Would it be possible to use a higher TTL than 60s for this data?

2023-03-23 20:51 UTC, closed without merging