Flighttracker - Initial push to Github
tidbyt/community pull request #1150
Opened 2023-02-20 15:30 UTC by SamuelSagarino

Flight tracking app; allowing users to input a flight number or airport ICAO code along with their FlightAware API key allowing them to track a specific flight - or see latest departures / arrivals from a specified airport.

2023-02-20 16:53 UTC, SamuelSagarino commented
I have read the CLA Document and I hereby sign the CLA

2023-02-23 23:07 UTC, SamuelSagarino commented
Update on 2/23 - Saw notes on some other PRs about caching and how it is not individual to the user. Made some adjustments to account for this and correct it.

2023-03-02 16:44 UTC, matslina requested changes
Thanks for the PR! Need just a little bit of additional caching. Also, could you add a default graphic for the case when no config is provided? That would allow users to see a preview and get a sense of whether or not this is an app they're willing to go get an API key for.

2023-03-02 16:44 UTC, matslina commented on apps/flighttracker/flighttracker.star
> +    logo = http.get("https://flightaware.com/images/airline_logos/90p/" + operator + ".png").body()  # Get logo to display.
Would be great with some caching around this call.

2023-03-04 15:51 UTC, SamuelSagarino commented
@matslina Added caching for the flight data; up to 120 seconds (if you think it should be more is there opposition to making it be a user definable cache length?), added caching for the airline images and added a resting look when an API key isn't present.

2023-03-14 18:56 UTC, matslina approved these changes

2023-03-14 18:56 UTC, matslina commented
120 is probably a good TTL. I don't think there's any reason to make that configurable yet, unless it turns out to be an issue down the road.

2023-03-14 18:57 UTC, merged