Initial check-in of TIX clock app
tidbyt/community pull request #1211
Opened 2023-03-13 20:04 UTC by pawliger

Initial check-in of the TIX clock app for Tidbyt. Displays the times using colorful blocks. Includes 12/24 hour clock settings and color theme choices.

2023-03-13 20:16 UTC, pawliger commented
I have read the CLA Document and I hereby sign the CLA

2023-03-13 20:16 UTC, pawliger commented
recheck

2023-03-14 20:07 UTC, matslina requested changes
Thanks for the PR. Looks great! A few comments inline.

2023-03-14 20:07 UTC, matslina commented on apps/tixclock/manifest.yaml
> +author: pawliger, original TIX Clock by James Thompson
```suggestion
author: pawliger
```

2023-03-14 20:07 UTC, matslina commented on apps/tixclock/manifest.yaml
> +desc: A Tidbyt version of the TIX clock. It uses arrays of colorful blocks to show the time.
```suggestion
desc: A Tidbyt version of the TIX clock. It uses arrays of colorful blocks to show the time. The original TIX Clock was invented by James Thompson.
```

2023-03-20 15:54 UTC, pawliger commented
Any thoughts when this might be reviewed? Thanks.

2023-03-23 12:08 UTC, matslina approved these changes

2023-03-23 12:09 UTC, merged