Adding Coinbase app
tidbyt/community pull request #1238
Opened 2023-03-20 16:56 UTC by harrywynn

Displays your current Coinbase balance and holdings.

![coinbase](https://user-images.githubusercontent.com/103879/226412753-e5081610-4655-4359-90ee-6776c472409d.gif)

2023-03-20 17:18 UTC, harrywynn commented
I have read the CLA Document and I hereby sign the CLA

2023-04-24 21:06 UTC, rohansingh requested changes
The cache is global and shared between all users. Please include a hash of the auth token in the cache key to scope it to the user.

2023-04-24 21:06 UTC, rohansingh commented on apps/coinbase/coinbase.star
> +COINBASE_CLIENT_ID = secret.decrypt("AV6+xWcE2JaB2O2ordBy0T1hLm/fb3TSEfrEpGojMFF9kazLU04l+4czjZcjg10VMPjMyr884buJOXY070nmqgiP55bdN7ZtT484avoKQqoF8aM3VnE4Y1Jw//51a36IEk2/uJBmqGfY90H7QlYBQ76zVAL5DWkuVL
Please use this client ID and secret:

```suggestion
COINBASE_CLIENT_SECRET = secret.decrypt("AV6+xWcEIOP/Rql2nyueyFjL9f51E2W1wDvcqtKyvXWRuSZwf7pNagbGLNridKAHG4Nw4oW2FZssbHNfsGwWAmSqXG3VN8oSvw0UY+4AB2LU3HMl5eEN9A139V08wU3/vOX7ouCUtHWwNkhHRngkQHqQiZSTK0KNOYTaIO9aeb7uzFwLdMdATDEQ2ypUjrvOt4l8UM1HIpXaIjn8T5bE+q7AYgaLww==")
COINBASE_CLIENT_ID = secret.decrypt("AV6+xWcEVIfI5lKs4wUCRh+CyWiA2VJ8Jngv8g/klexY7x7qR4KGIopsbZOIq/syABtfSToDA/nx5J8Mhy+XakIUjxESmr3V9fKOeymlJd7G/0VImVbAJYoZoTU2PMgzHcr7+HUV3SVUGrmZk62eMH5y77pWPb6MXIeLXAwTYFL6ZBk3NQCkP6EIN0dOP9h+ubvvBWMLE1U3Imc9ZdqxC4XPEQmPPg==")
```

2023-04-25 14:30 UTC, rohansingh approved these changes

2023-04-25 14:31 UTC, merged

2023-04-25 14:37 UTC, rohansingh commented
This is live now. Thanks for the contribution!