Split scores up to 8 app instances
tidbyt/community pull request #574
Opened 2022-08-02 01:05 UTC by cmarkham20

Added the ability for users to install the app up to 8 times and have the scores split between each instance.

2022-08-11 20:54 UTC, matslina requested changes
Hey there. Sounds like a neat change, but it looks like this PR has gone a bit haywire?
<img width="131" alt="image" src="https://user-images.githubusercontent.com/208392/184240348-e8621772-4cd7-41b6-91f9-b8bec49fe1d6.png">
<img width="133" alt="image" src="https://user-images.githubusercontent.com/208392/184240377-81ce72f3-2d15-44d3-af5c-e7565d8ecc60.png">
=)

2022-08-12 18:59 UTC, cmarkham20 reviewed
While yes, there are quite a few changes, the are mainly the same changes across the 6 "scores" apps, and there are 3 new Standings apps. Of these apps work well on my testing environments. I'm not 100% sure how to open separate PRs for each but will look to do so in the future.

2022-08-13 12:42 UTC, cmarkham20 commented
@matslina Let me know what I can do to push this through... Again, there are a lot of apps within this PR hence amount of files.

2022-08-18 14:50 UTC, matslina approved these changes

2022-08-18 14:51 UTC, merged