Statuspage.io
tidbyt/community pull request #594
Opened 2022-08-17 04:35 UTC by DigitallyBorn

Display simple status from an Atlassian Status Page (aka statuspage.io).

![statuspage](https://user-images.githubusercontent.com/16527/185034463-5feeb24a-e847-4483-a5ff-ac40788dfeb7.gif)
![statuspage](https://user-images.githubusercontent.com/16527/185034609-1e52f6ee-db7c-4766-83ce-63d32be954d7.gif)
![statuspage](https://user-images.githubusercontent.com/16527/185034654-6c34009f-eb49-4d56-8112-914f9fec1e27.gif)

2022-08-18 18:33 UTC, matslina requested changes
Wonderful idea, but I'm afraid we currently can't merge apps that call user-provided URLs. Since community apps run in our backend, we have to make sure HTTP calls hit predictable targets to make sure we're not inadvertently spamming anyone.

One option could be to predefine some popular/significant status pages in the code and make it available to the user as a Dropdown? Alternatively, if statuspage.io has some list of sites, then that could be used in a similar fashion.

2022-08-19 00:54 UTC, DigitallyBorn commented
> Wonderful idea, but I'm afraid we currently can't merge apps that call user-provided URLs. Since community apps run in our backend, we have to make sure HTTP calls hit predictable targets to make sure we're not inadvertently spamming anyone.
> 
> One option could be to predefine some popular/significant status pages in the code and make it available to the user as a Dropdown? Alternatively, if statuspage.io has some list of sites, then that could be used in a similar fashion.

That makes sense. Unfortunately, I don't know of a safe way to verify that a URL is an Atlassian-hosted status page with the tools on hand. They do host cheap/free statuspages on `[whatever].statuspage.io`, but nearly all businesses using it use their own domain.

Just thinking about ways of verifying ...
- Verification of CNAME entry in DNS won't be reliable. Customers could point traffic through their own CDN or flatten DNS.
- Verification of the SSL certificate won't even work -- they use Let's Encrypt and don't create a single certificate for each domain -- one of my statuspage has 40 domains included in the same certificate.
- They don't supply reverse DNS entries (ptr records), so we can't do a reverse lookup on the server's IP (it just identifies as a generic AWS EC2 instance/endpoint).

I'm out of ideas. That's sad ... I had memories of a big glowing green box in a data center showing that everything was happy.

2022-08-25 14:22 UTC, matslina commented
While I hope we'll be able to allow user provided URLs in the future, it'll take a while to get there as there are many competing priorities. The CNAME check would certainly do the job in this particular case, but ideally we'd find a more general solution to the problem.

But I'm thinking it might not be such a bad idea to have a predefined list of status pages to choose from. It'll certainly make the app a lot more accessible to non-technical users, while opening up for technical users to submit a PR to add a new status page to the list. It'd also provide some sense of discoverability to the app. For instance, here's what I found in a few minutes:

```
status.amplitude.com
status.atlassian.com
status.appsflyer.com
status.box.com
www.cloudflarestatus.com
status.datadoghq.com
discordstatus.com
status.fastly.com
status.grammarly.com
www.pintereststatus.com
www.redditstatus.com
status.sumsub.com
api.twitterstat.us
status.udemy.com
status.zoom.us
```

All appear to be on statuspage.io. I suspect few users would actively go look if Discord was on statuspage.io, but I bet quite a few would happily start tracking it if it was already in the list. WDYT?

2022-08-25 17:58 UTC, jvivona commented
we will watch for the commit to main and then add other services we know of (teamviewer, some of the large VoIP providers, etc)

2022-09-26 01:21 UTC, closed without merging