Add Roblox app
tidbyt/community pull request #660
Opened 2022-09-15 04:02 UTC by C0DESTR0NG

# Roblox for Tidbyt

Displays an online friends or favorite games view for a specified Roblox username.

A pulsating green dot will appear if the Roblox user is online, otherwise it will show gray for offline. Friend avatars also provide an online vs offline dot indicator.

### ONLINE FRIENDS VIEW

![Sample Online Friends View](https://www.dropbox.com/s/3na6toovhxn6kc0/roblox_friends.gif?raw=1)

### FAVORITE GAMES VIEW

![Sample Favorite Games View](https://www.dropbox.com/s/pbdxea94fqya76g/roblox_favorite_games.gif?raw=1)

### Customization

This app provides various UI options. The user can customize their experience by choosing to show their online friends vs. favorite games views, selecting an accent text color or enabling dark vs. light modes.  

These customizations can be adjusted using the properties of the app.

2022-09-15 04:06 UTC, C0DESTR0NG commented
I have read the CLA Document and I hereby sign the CLA

2022-09-15 20:01 UTC, matslina requested changes
Hey, this looks really promising! The layout is very spiffy! =)

There are some issues with caching that I think we need addressed before merging. See the individual code comments for more context. If you find this confusing, feel free to ask questions in the comments here, or hit me up via DM on discord.

2022-09-15 22:07 UTC, C0DESTR0NG commented on apps/roblox/roblox.star
> +    user_id_cached = cache.get("user_id")
Great call out. I removed clearCaches() and updated the caches to use username as a key per your request. Now included in latest commit.

2022-09-15 22:07 UTC, C0DESTR0NG commented on apps/roblox/roblox.star
> +        cache.set("user_favorite_games_list", json.encode(userFavoriteGames), ttl_seconds = TTL_SECONDS)
These cache setters have also been updated in the latest commit 👍🏼

2022-09-17 05:46 UTC, C0DESTR0NG commented on apps/roblox/roblox.star
> +    profilePhotoImg = http.get(profilePhotoUrl).body() if profilePhotoUrl != "" else ""
@matslina Now caching **all** _user_, _friend_ and _game_ image data by key. Seeing much faster load times between app config updates. Thank you!

2022-09-22 16:04 UTC, matslina approved these changes

2022-09-22 16:04 UTC, merged