New app: Zenhub
tidbyt/community pull request #690
Opened 2022-09-26 08:33 UTC by thiagobrez

Integrate your [Zenhub](https://www.zenhub.com/) workspace to the Tidbyt display.

Zenhub is a productivity management tool to keep track of issues and features like Jira, Asana, Azure DevOps. Using your Zenhub API Keys, we can pull information from your workspace and show in your Tidbyt display.

- Choose a pipeline to display issues (tickets)
- Filter by labels
- Filter by assignees

![zenhub](https://user-images.githubusercontent.com/26878038/192229689-36dda6c9-b0f9-44dd-9741-faa609f6abf1.gif)

- In the top row
  - Show the chosen pipeline. Can be any pipeline in your Zenhub workspace. In this example: "Current Sprint"
- In center
  - Show the first 3 issues (tickets) in the pipeline. Issue number and title

2022-09-26 08:35 UTC, thiagobrez commented
I have read the CLA Document and I hereby sign the CLA

2022-09-28 22:40 UTC, thiagobrez commented
Included MD5 hash of user's api key in the cache key, per comments in other PRs

2022-09-29 20:02 UTC, matslina requested changes
Hey, thanks for the PR!

I've added a few comments in the code, and of course the build is failing but that should be a simple fix I think. When we get it merged, feel free to ping me on discord and I'll get you set up with beta access so you can test it out in production before we publish it. I miiiight set up my own Zenhub account for testing, but maybe not. =)

2022-09-29 23:57 UTC, thiagobrez commented on apps/zenhub/zenhub.star
> +    if not zenhub_rest_api_key:
Hey, Mats! Thanks for the review. Nice suggestion, I added a welcome page with fake tasks guiding the user to set-up the configuration info, like below:

https://user-images.githubusercontent.com/26878038/193160949-91a31a78-12fd-4c57-bf56-42236f915f53.mov

2022-09-29 23:58 UTC, thiagobrez commented on apps/zenhub/zenhub.go
> +		Desc:        "Show Zenhub issues from a Pipeline of your choice. Filter by labels and assignees.",
Yeah, I imagined this could be a thing. I moved the guides to the description, see if that works!

2022-09-30 00:18 UTC, thiagobrez commented
Fixed the build and the other requested changes. Let me know what you think!

2022-10-06 15:30 UTC, matslina approved these changes

2022-10-06 15:30 UTC, merged