New App: MCServerStatus
tidbyt/community pull request #758
Opened 2022-10-26 06:09 UTC by jakeva

Track the player count of any Minecraft server!

An example of tracking the Hypixel Network:
<img width="961" alt="display" src="https://user-images.githubusercontent.com/5650707/197947403-b5d1b064-46a1-4757-8263-f57cbcc5d69c.png">

If a server has a logo, it will use that as the image displayed. If not, it will display a default image, which is a Minecraft Grass Block. If a server is offline, it will display a Minecraft Barrier Block icon and "Offline" text.

With this initial build, only Java Minecraft Servers are supported.

2022-10-26 06:09 UTC, jakeva commented
I have read the CLA Document and I hereby sign the CLA

2022-11-11 02:22 UTC, jakeva commented
@matslina My apologies, had it as a draft PR due to the automatic testing action failing. Ready to be reviewed now! 😄

2022-11-17 18:44 UTC, matslina requested changes
Thanks for the PR! Two notes on changes we need in place before merging.

2022-11-17 18:44 UTC, matslina commented on apps/mcserverstatus/mcserverstatus.star
> +    req = http.get("https://api.mcsrvstat.us/" + ("bedrock/" if minecraft_edition else "") + "2/" + server_ip + (":" + server_port if server_port else ""))
Some caching here would be good! Don't want to unnecessarily hammer the API.

2022-11-17 18:44 UTC, matslina commented on apps/mcserverstatus/mcserverstatus.star
> +    if req.status_code != 200:
Would be great if the app could show some illustrative default graphic when no configuration has been passed. That enables users to see previews of the app before deciding to configure and install it.

2022-12-05 14:46 UTC, closed without merging