New app: Spinbyt
tidbyt/community pull request #766
Opened 2022-10-30 15:22 UTC by zachlucas

This is an app to show information about the nearest [Spin](https://www.spin.app) scooters. Takes two inputs, a specific location for which to check for scooters, and the city in which your Spin service is in.

It calls the Spin API that uses the GBFS standard: https://github.com/MobilityData/gbfs/blob/v2.3/gbfs.md

## Screenshots

<img width="511" alt="spinbyt-2" src="https://user-images.githubusercontent.com/3679572/198886718-d92c1acb-8b24-4bf9-8d5e-c4f34ecfb20b.png">

![spinbyt-explainer](https://user-images.githubusercontent.com/3679572/198886719-64367f3b-4813-4837-9f38-c815fe470343.png)

2022-10-30 15:23 UTC, zachlucas commented
I have read the CLA Document and I hereby sign the CLA

2022-11-08 17:17 UTC, zachlucas commented
@betterengineering Hi! Would be curious to hear y'all's thoughts on this - anything that I can improve or change here? Thanks!

2022-11-10 14:25 UTC, matslina commented on apps/spinbyt/spinbyt.star
> +    rep = http.get(url)
We'll need a bit of caching around this call to make sure we're not hammering the API too much. Every Tidbyt running the app will trigger one execution of `main()` each time the app is on display, so caching is essential to keep request rates down.

2022-11-10 14:28 UTC, matslina requested changes
Hey @zachlucas. Thanks for the PR! And our apologies for the delay. We usually try to merge PRs once a week, but the last 2 weeks have been especially hectic and we're behind!

This looks great. Just the one comment on caching and I think we're good to go.

2022-11-11 16:44 UTC, zachlucas commented on apps/spinbyt/spinbyt.star
> +    rep = http.get(url)
Makes sense, I see caching recommendations [here](https://tidbyt.dev/docs/build/crypto-tracker#caching), I'll try that approach. Thanks

2022-11-14 14:57 UTC, zachlucas commented on apps/spinbyt/spinbyt.star
> +    rep = http.get(url)
<img width="481" alt="Screenshot 2022-11-14 at 9 56 38 AM" src="https://user-images.githubusercontent.com/3679572/201692102-6e12d221-4f6d-482c-aea6-7b8b9a387a35.png">

Looks good!

2022-11-17 18:45 UTC, matslina approved these changes

2022-11-17 18:45 UTC, merged