Stupid Chat for Tidbyt
tidbyt/community pull request #836
Opened 2022-11-26 22:40 UTC by harrisonpage

Send messages and pictures to your Tidbyt from anywhere.

Visit https://stupid.chat and click `Get Started`.  You will be assigned a random, unique token for your Tidbyt. Configure your stupid.chat token in the app to link the website to your device. Having done so, you may send messages or images from the stupid.chat website to your Tidbyt.  Tokens are free, you can always visit stupid.chat and generate a new one.

2022-11-26 22:42 UTC, harrisonpage commented
recheck

2022-11-26 22:44 UTC, harrisonpage commented
I have read the CLA Document and I hereby sign the CLA

2022-11-28 13:51 UTC, matslina requested changes
Thanks for the PR! This looks great, and I'm sure folks will enjoy it a lot! =)

A few comments that needs to be addressed before we merge. Also wanted to mention that I've seen a lot of 500s when testing this out locally. Both with the default token and a new one I created on the site. Might be good to take a look at that, in case there something that needs fixing on your end for this to work more reliably.

2022-11-28 13:51 UTC, matslina commented on apps/stupidchat/stupid_chat.star
> +        fail("failed with status %d", response.status_code)
```suggestion
        fail("failed with status %d" % response.status_code)
```

2022-11-28 13:51 UTC, matslina commented on apps/stupidchat/stupid_chat.star
> +    token = get_config(config, "token", "WELCOME")
The config (dict like) object can handle the default case for you:
```suggestion
    token = config.get("token", "WELCOME")
```

2022-11-28 13:51 UTC, matslina commented on apps/stupidchat/stupid_chat.star
> +    client_id = get_config(config, "client_id", "XXX")
I take it this is for debug purposes? Just wanted to mention since it's not in the schema.

2022-11-28 13:51 UTC, matslina commented on apps/stupidchat/stupidchat.go
> +		Summary:     "Tidbyt Messaging",
If you don't mind it'd be great to rephrase this summary a little bit, just to highlight to users that this an external service not provided by Tidbyt. Perhaps something like `"Send messages to your Tidbyt"`?

2022-11-28 13:51 UTC, matslina commented on apps/stupidchat/stupidchat.go
> +		Desc:        "Send messages to your Tidbyt via https://stupid.chat or an API.",
Could you also add a note in the description highlighting that the Stupid Chat service is external and not run by Tidbyt? You can see a similar example in the "Textbyt" app.

2022-11-29 09:10 UTC, matslina commented on apps/stupidchat/stupidchat.go
> +		Summary:     "Tidbyt Messaging",
```suggestion
		Summary:     "Send messages to your Tidbyt",
```

2023-01-06 01:25 UTC, closed without merging