New App: Last.fm Now Playing
tidbyt/community pull request #980
Opened 2023-01-18 16:46 UTC by MattyGroch

Adding a new app that supports whatever track a user is currently scrobbling to their Last.fm account. As someone who doesn't use Spotify, this is a nice alternative to a "Now Playing" app. The app uses my own Last.fm API key to make requests but users are allowed (not required) to supply their own API key.

2023-01-18 18:38 UTC, MattyGroch commented
I also noticed that *.gif is listed in the .gitignore, yet it seems to be how several other applications are hosting their screenshot for the readme.md. If you would prefer I self-host the screenshot and link it instead of adding it to this repo, let me know.

2023-01-24 04:04 UTC, doubleyuhtee approved these changes

2023-01-24 16:34 UTC, matslina requested changes
Hey there, thanks for the PR!

The secret doesn't seem to decrypt properly. Could you share the command line you used when creating it (with the secret value redacted)?

2023-01-24 18:26 UTC, MattyGroch commented on apps/idlegardener/idle_gardener.star
> +    """\r
Yes, I believe I originally submitted the secret under the "Last.fm" name, not the "Lastfm" name. I'll encrypt a new secret and update the key in the file.

2023-02-21 15:19 UTC, closed without merging